apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chromium-service
  labels:
    app: chromium
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chromium
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}

